version: "3.9"
services:
  api:
    build: 
      args: 
        user: sefas
        uid: 1001
      context: ./api
      dockerfile: ./Dockerfile
    image: laravelapp
    hostname: api
    container_name: kokoro-api
    restart: unless-stopped
    working_dir: /var/www/
    environment: 
        DB_HOST: db
        DB_PORT: 3306
        DB_DATABASE: 'kokoroapp'
        DB_USERNAME: 'root'
        DB_PASSWORD: 'root'
        DB_CONNECTION: mysql
    volumes:
      - ./api:/var/www
      - ./.docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    image: mysql:8.0.21
    hostname: db
    container_name: kokoro-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'kokoroapp'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'lara_password'
      MYSQL_USER: 'lara_user'
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql:/var/lib/mysql

  nginx:
    image: nginx:1.17-alpine
    hostname: nginx
    container_name: kokoro-nginx
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./api:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d

  ui:
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    image: kokoro-ui
    hostname: ui
    container_name: kokoro-ui
    restart: unless-stopped
    ports:
      - 80:80
    volumes: 
      - ./ui:/var/www